-- AlterTable
ALTER TABLE "SiteSetting" ADD COLUMN IF NOT EXISTS "phone" TEXT;
ALTER TABLE "SiteSetting" ADD COLUMN IF NOT EXISTS "workingHours" TEXT;
ALTER TABLE "SiteSetting" ADD COLUMN IF NOT EXISTS "website" TEXT;
ALTER TABLE "SiteSetting" ADD COLUMN IF NOT EXISTS "mapsCoords" TEXT;
ALTER TABLE "SiteSetting" ADD COLUMN IF NOT EXISTS "googleAnalytics" TEXT;
ALTER TABLE "SiteSetting" ADD COLUMN IF NOT EXISTS "googleWebmaster" TEXT;
ALTER TABLE "SiteSetting" ADD COLUMN IF NOT EXISTS "headJs" TEXT;
ALTER TABLE "SiteSetting" ADD COLUMN IF NOT EXISTS "bodyJs" TEXT;
ALTER TABLE "SiteSetting" ADD COLUMN IF NOT EXISTS "seoKeywords" TEXT;
ALTER TABLE "SiteSetting" ADD COLUMN IF NOT EXISTS "primaryKeyword" TEXT;
ALTER TABLE "SiteSetting" ADD COLUMN IF NOT EXISTS "mailerHost" TEXT;
ALTER TABLE "SiteSetting" ADD COLUMN IF NOT EXISTS "mailerPort" TEXT;
ALTER TABLE "SiteSetting" ADD COLUMN IF NOT EXISTS "mailerSecure" TEXT;
ALTER TABLE "SiteSetting" ADD COLUMN IF NOT EXISTS "mailerEmail" TEXT;
ALTER TABLE "SiteSetting" ADD COLUMN IF NOT EXISTS "mailerPassword" TEXT;
