-- AlterTable
ALTER TABLE "Post" ADD COLUMN IF NOT EXISTS "sortOrder" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Post" ADD COLUMN IF NOT EXISTS "isNew" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Post" ADD COLUMN IF NOT EXISTS "isFeatured" BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE "Post" ADD COLUMN IF NOT EXISTS "isVisible" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Post" ADD COLUMN IF NOT EXISTS "tags" TEXT;
ALTER TABLE "Post" ADD COLUMN IF NOT EXISTS "seoKeywords" TEXT;
ALTER TABLE "Post" ADD COLUMN IF NOT EXISTS "canonicalUrl" TEXT;
ALTER TABLE "Post" ADD COLUMN IF NOT EXISTS "publishedAt" TIMESTAMP(3);

CREATE INDEX IF NOT EXISTS "Post_type_sortOrder_idx" ON "Post"("type", "sortOrder");
